name: Simple Code

on: 
  push: { }

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Add your build commands here

      - name: Test
        run: |
          # Add your test commands here
          echo "hello"
